services:
  agent:
    image: "${AGENT_NAME}-agent"  # Unique image name per agent
    build: .
    container_name: "${AGENT_NAME}-agent"  # Unique container name
    environment:
      - API_KEY=${API_KEY}
      - AGENT_NAME=${AGENT_NAME}
    ports:
      - "5000:5000"  # Custom external port